"""Type stubs for the mixpy public API."""

from typing import Any, Callable, Sequence, overload
from mixpy.model import At, TYPE, OP, Loc, When, POLICY, OCCURRENCE
from mixpy.selector import (
    NameSelector, QualifiedSelector, ConstSelector, AttrSelector,
    CallSelector, ArgAny, ArgConst, ArgName, ArgAttr, KwPattern,
    ARGS_MODE, KW_MODE, STARSTAR_POLICY,
)
from mixpy.location import SliceSpec, NearSpec, AnchorSpec, LineSpec
from mixpy.errors import MixinConflictError, MixinMatchError

__version__: str

# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------

def configure(
    *,
    debug: bool | None = ...,
    trace: bool | None = ...,
    source_dump_dir: str | None = ...,
) -> None: ...

def init(*, debug: bool | None = ...) -> None: ...

# ---------------------------------------------------------------------------
# Decorators
# ---------------------------------------------------------------------------

def mixin(
    target: str | type | list[str | type],
    *,
    priority: int = ...,
) -> Callable[[type], type]: ...

def inject(
    *,
    method: str,
    at: At,
    priority: int = ...,
    require: int | None = ...,
    expect: int | None = ...,
    policy: POLICY = ...,
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

# ---------------------------------------------------------------------------
# At-builders (shorthand)
# ---------------------------------------------------------------------------

def at_head(*, location: Loc | None = ...) -> At: ...
def at_tail(*, location: Loc | None = ...) -> At: ...
def at_parameter(name: str, *, location: Loc | None = ...) -> At: ...
def at_const(value: Any, *, location: Loc | None = ...) -> At: ...
def at_invoke(name: str, *, selector: CallSelector | None = ..., location: Loc | None = ...) -> At: ...
def at_attribute(name: str, *, location: Loc | None = ...) -> At: ...
def at_exception(*, location: Loc | None = ...) -> At: ...
def at_yield(*, location: Loc | None = ...) -> At: ...

# ---------------------------------------------------------------------------
# Inject-decorators (shorthand)
# ---------------------------------------------------------------------------

def inject_head(*, method: str, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_tail(*, method: str, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_parameter(*, method: str, name: str, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_const(*, method: str, value: Any, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_invoke(*, method: str, name: str, selector: CallSelector | None = ..., location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_attribute(*, method: str, name: str, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_exception(*, method: str, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...
def inject_yield(*, method: str, location: Loc | None = ..., **kw: Any) -> Callable[..., Any]: ...

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def target_path(target: str | type) -> str: ...
def unregister_injector(target: str, method: str, callback: Callable[..., Any]) -> bool: ...
def reload_target(target: str) -> None: ...
def generate_stubs(target: str, out_dir: str = ...) -> None: ...
def log(level: str, message: str) -> None: ...
